name             "supu-io"
maintainer       "Adrià Cidre"
maintainer_email "adria.cidre@gmail.com"
license          "Apache 2.0"
description      "Installs/configures supu.io"
version          "0.1.0"
recipe           "supu-io::default", "Installs/configures supu.io"
